services:
  db:
    image: mysql:8.0
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: citaonica
      MYSQL_ROOT_PASSWORD: "itehhh"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=itehhh

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - TZ=Europe/Belgrade
      - EMAIL_USER=jovanbojanic48@gmail.com
      - EMAIL_PASS=tqzl yhvn ipnh tqjj
      - DB_HOST=db
      - DB_NAME=citaonica
      - DB_USER=root
      - DB_PASS=itehhh
    depends_on:
      db:
        condition: service_healthy

  scraper:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"
    command: >
      sh -c "pip install --no-cache-dir requests beautifulsoup4 mysql-connector-python && 
             python3 scraper.py"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --turbopack
    depends_on:
      - backend
